services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'

    volumes:
      - ./path\ to/src/main/resources/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - '3306'
